services:
  postgres:
    image: postgres:16-alpine
    container_name: upj-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: upj
      POSTGRES_PASSWORD: upj_secret
      POSTGRES_DB: upj_control
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
